name: Release script
on:
  push:
    branches: 
      - release/*
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '1'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
            path: '**/node_modules'
            key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
            
      - name: Set version
        run: yarn version --new-version ${{ github.event.release.tag_name }}
  
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build:chrome
        
      - name: Upload build
        uses: actions/upload-artifact@v3.1.2
        with:
            name: 'auto-tab-mute-chrome-${{ github.event.release.tag_name }}.zip'
            file: '**/extensions/chrome.zip'