on:
  push:
    branches:
      - main

jobs:
  build-and-convert:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn and Dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build Web Extension
        run: yarn run build

      - name: Convert Web Extension to Safari
        run: |
          xcrun safari-web-extension-converter --project-location ./safari-extension --macos-only ./extension/chrome

      - name: Build Safari Extension
        if: success()
        run: |
          cd safari-extension/Auto\ Tab\ Mute.xcodeproj
          xcodebuild -scheme "Auto Tab Mute" -configuration Release build ARCHIVE_PATH=./build/AutoTabMute.xcarchive

      - name: Archive Safari Extension Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: safari-extension-build
          path: |
            safari-extension/build/Release/*.app
            safari-extension/build/Release/*.appex